# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "feeds", :force => true do |t|
    t.column "url",         :string,  :default => "", :null => false
    t.column "name",        :string,  :default => "", :null => false
    t.column "source_id",   :integer, :default => 0,  :null => false
    t.column "topic_id",    :integer, :default => 0,  :null => false
    t.column "html_url",    :string,  :default => "", :null => false
    t.column "description", :text
  end

  create_table "source_types", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
  end

  add_index "source_types", ["name"], :name => "index_source_types_on_name", :unique => true

  create_table "sources", :force => true do |t|
    t.column "name",           :string,  :default => "", :null => false
    t.column "slug",           :string,  :default => "", :null => false
    t.column "source_type_id", :integer, :default => 0,  :null => false
  end

  add_index "sources", ["name"], :name => "index_sources_on_name", :unique => true
  add_index "sources", ["slug"], :name => "index_sources_on_slug", :unique => true

  create_table "topics", :force => true do |t|
    t.column "name", :string, :default => "", :null => false
    t.column "slug", :string, :default => "", :null => false
  end

  add_index "topics", ["name"], :name => "index_topics_on_name", :unique => true
  add_index "topics", ["slug"], :name => "index_topics_on_slug", :unique => true

end
